package net.idik.lib.cipher.so.generater

import net.idik.lib.cipher.so.extension.KeyExt
import net.idik.lib.cipher.so.utils.AESEncryptor
import net.idik.lib.cipher.so.utils.StringUtils

class CipherSoHeaderBuilder {
    private List<KeyExt> keys
    private String signature = ""
    private String fileName
    private String secretKey = ""
    private String iv = ""

    CipherSoHeaderBuilder(String fileName, List<KeyExt> keys) {
        this.fileName = fileName
        this.keys = keys
    }

    CipherSoHeaderBuilder setSignature(String signature) {
        this.signature = signature
        this
    }

    CipherSoHeaderBuilder setSecretKey(String secretKey) {
        this.secretKey = secretKey
        this
    }

    CipherSoHeaderBuilder setIv(String iv){
        AESEncryptor.setIv(iv)
        this.iv = iv
        this
    }

    List<String> build() {
        List<String> lines = new ArrayList<>()
        def headerName = fileName.replaceAll("\\.", "_").replaceAll("-", "_").toUpperCase(Locale.US)
        lines.add("// Auto-Generated By Cipher.so - 林帅斌(me@idik.net)\n\n")
        lines.add("#ifndef $headerName\n")
        lines.add("#define $headerName\n\n")

        lines.add("#define SIGNATURE \"${signature}\"\n")

        lines.add("#define LOAD_MAP(_map) \\\n")
        lines.add("    _map[\"key_s\"] = \"$secretKey\"; \\\n")
        lines.add("    _map[\"iv\"] = \"$iv\"; \\\n")

        keys.each {
            lines.add("    _map[\"${StringUtils.md5(it.name)}\"] = \"${AESEncryptor.enc(secretKey, it.value)}\"; \\\n")
        }
        lines.add("\n")
        lines.add("#endif //$headerName\n\n")
        lines
    }
}